import type { Metadata } from "next";
import { News_Cycle } from "next/font/google";
import '../style/index.scss'
const newsCycle = News_Cycle({ weight: "400", subsets: ['latin']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={newsCycle.className}>{children}</body>
    </html>
  );
}
